### ISSUE TITLE
Fatal error with post count

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/Tag-Groups#69]
Not solved yet:

[10-Apr-2023 00:02:06 UTC] PHP Fatal error Uncaught Error: Cannot use string offset as an array in /var/www/html/soretrostraps/wp-content/plugins/tag-groups-pro/premium/include/admin/runners/class.premium_post_count_tools.php:156

https://secure.helpscout.net/conversation/2208721324/180441?folderId=4410099

**Comment by ojopaul** [comment]
@stevejburge Do we see how to trigger this issue?

**Comment by stevejburge** [comment]
@ojopaul Sorry, I have seen this live, but not in my testing. It cold be related to old data

This user wanted a refund so I'm tempted to wait for another example. I'll remove from the milestone for now.

**Comment by ojopaul** [comment]
@stevejburge I've been able to recreate this issue when saving terms changing tag groups option in php 8.1

<img width="1154" alt="ppp" src="https://github.com/TaxoPress/Tag-Groups/assets/92122385/b6f3935a-2480-4723-b6b6-150834e4a451">
